services:
  nginx:
    build: ./containers/nginx
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - ./backend/static:/var/lib/nginx/static
    networks:
      - pong
    ports:
      - 443:443
    depends_on:
      - django
    env_file:
      - .env

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: on-failure
    volumes:
      - pongdb:/var/lib/postgresql/data
    networks:
      - pong
    env_file:
      - .env

  django:
    build: ./containers/django
    image: django
    container_name: django
    restart: on-failure
    volumes:
      - ./backend:/usr/local/django/pong-backend
    networks:
      - pong
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pongdb:

networks:
  pong:
    name: pong
    driver: bridge
