name: Project set up check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Build and bring up the Docker Compose services
      run: make up

    - name: Tear down the Docker Compose services
      run: make down

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install make
        brew install --cask docker

    - name: Start Docker
      run: open /Applications/Docker.app

    - name: Wait for Docker to start
      run: |
        while ! docker info > /dev/null 2>&1; do sleep 1; done

    - name: Build and bring up the Docker Compose services
      run: make up

    - name: Tear down the Docker Compose services
      run: make down
