name: Project set up check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Create .env file
      run: |
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "DJANGO_KEY=${{ secrets.DJANGO_KEY }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

    - name: Build and bring up the Docker Compose services
      run: make up

    - name: Tear down the Docker Compose services
      run: make down

    - name: Remove .env file
      run: rm -f .env
